name: idrid-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.12
  
  # Core Data Science
  - numpy
  - pandas
  - matplotlib
  - seaborn
  
  # Image Processing
  - pillow
  - opencv
  
  # Machine Learning
  - scikit-learn
  
  # Deep Learning
  - pytorch
  - torchvision
  
  # Jupyter
  - jupyter
  - ipykernel
  
  # Progress Bars
  - tqdm
  
  # Pip packages (not available in conda)
  - pip
  - pip:
    - fiftyone
    - umap-learn
